# nginx proxy address - http://172.17.0.1:3002

x-logging: &default-logging
  driver: json-file
  options:
    max-size: "5m"
    max-file: "1"

services:
  forgejo:
    image: codeberg.org/forgejo/forgejo:latest
    container_name: forgejo-app
    restart: unless-stopped
    logging: *default-logging
    networks:
      - forgejo
    ports:
      - "3002:3000"
    environment:
      TZ: ${TZ:-America/New_York}
      DATABASE_URL: postgres://${DB_USER_NAME:-forgejo}:${DB_USER_PASS:-changeme_db_password}@forgejo-db:5432/${DB_CREATE_DATABASE_NAME:-forgejo}
    volumes:
      - ./rootfs/data/forgejo:/data
      - ./rootfs/config/forgejo:/config
    depends_on:
      - forgejo-db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

  forgejo-db:
    image: postgres:16-alpine
    container_name: forgejo-db
    restart: unless-stopped
    logging: *default-logging
    networks:
      - forgejo
    environment:
      TZ: ${TZ:-America/New_York}
      POSTGRES_DB: ${DB_CREATE_DATABASE_NAME:-forgejo}
      POSTGRES_USER: ${DB_USER_NAME:-forgejo}
      POSTGRES_PASSWORD: ${DB_USER_PASS:-changeme_db_password}
    volumes:
      - ./rootfs/db/postgres/forgejo:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  forgejo:
    external: false
